# .github/workflows/build-and-deploy.yml
name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 或者你使用的分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs

    - name: Build MkDocs site
      run: mkdocs build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages  # The branch the action should deploy to.
        folder: site      # The folder the action should deploy.
        clean: true       # Automatically remove deleted files from the deployment
        token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions


site_name: My Documentation
site_url: https://yourusername.github.io/my-project/

nav:
  - Home: index.md
  - Model A:
    - Combined Document: modelA_combined.md
